## GNU Make 3.81
## Copyright (C) 2006  Free Software Foundation, Inc.
## This is free software; see the source for copying conditions.
## There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
## PARTICULAR PURPOSE.
##
## This program built for i386-apple-darwin11.3.0
##
## Targeting amd64 machine type and gnu linux system
TARGET := aarch64-gnu-linux
SYSROOT := /

SRC_FILES := $(wildcard *.c)
CROSS_OBJS := $(SRC_FILES:.c=-$(TARGET))

CXX_SRC_FILES := $(wildcard *.cc)
CXX_CROSS_OBJS := $(CXX_SRC_FILES:.cc=-$(TARGET))

CC ?= clang
CXX ?= clang++

CPPFLAGS := -DNDEBUG -D_FORTIFY_SOURCE=2
CFLAGS := $(CPPFLAGS) -O3 --target=$(TARGET) --sysroot $(SYSROOT) -std=c99
CXXFLAGS := $(CPPFLAGS) -O3 --target=$(TARGET) --sysroot $(SYSROOT) -std=c++20
LDFLAGS := -fuse-ld=lld

ifneq ($(findstring freebsd,$(TARGET)),)
	LDFLAGS += -Wl,-L$(PWD)/freebsd
endif

.PHONY: all clean

all : $(CROSS_OBJS) $(CXX_CROSS_OBJS)

%-$(TARGET): %.c
	$(CC) -o $@ $^ $(CFLAGS) $(LDFLAGS)

%-$(TARGET): %.cc
	$(CXX) -o $@ $^ $(CXXFLAGS) $(LDFLAGS)

clean:
	-rm -f $(CROSS_OBJS) $(CXX_CROSS_OBJS)
